#!/usr/bin/env bash

#################################################
##
## This script copies dotfiles and other things
## to backup repo.
##
#################################################

BACKUP_FOLDER="$HOME/repos/dotfiles-mac"
SUBLIME="$HOME/Library/Application*Support/Sublime*Text*3/Packages"
# SUBLIME="$HOME/Library/Application Support/Sublime Text 3/Packages"

function backup {
  create_folders
  backup_dotfiles
  backup_sublime
  backup_karabiner
}

function create_folders {
  mkdir -p $BACKUP_FOLDER/dotfiles
  mkdir -p $BACKUP_FOLDER/sublime_3
}

function backup_dotfiles {
  FILES=('.zshrc' '.bash_aliases' '.bash_env' '.vimrc' '.tmux.conf')

  for file in "${FILES[@]}"; do
    cp $HOME/$file $BACKUP_FOLDER/dotfiles
  done
}

function backup_sublime {
  rm -rf $BACKUP_FOLDER/Sublime_3
  mkdir -p $BACKUP_FOLDER/Sublime_3/User

  cp -r $SUBLIME/Themes $BACKUP_FOLDER/Sublime_3

  # copy all folders
  find $SUBLIME/User/* -type d -maxdepth 0 -exec cp -r {} $BACKUP_FOLDER/Sublime_3/User \;
  # copy all sublime-settings files
  cp $SUBLIME/User/*.sublime-settings $BACKUP_FOLDER/Sublime_3/User/
  # copy other files
  cp $SUBLIME/User/*.sublime-keymap $SUBLIME/User/*.json $BACKUP_FOLDER/Sublime_3/User/

  rm -rf $BACKUP_FOLDER/Sublime_3/User/Color\ Highlighter
}

function backup_karabiner {
  /Applications/Karabiner.app/Contents/Library/bin/karabiner export > $BACKUP_FOLDER/presets/carabiner.sh
}

$@
