#!/usr/bin/env bash

function install_mysql {
  brew install mysql
  update_mysql_configuration
}

function update_mysql_configuration() {
  MYSQL_DIR="/etc/mysql"
  MYSQL_CONFIG_FILE="${MYSQL_DIR}/my.cnf"

  if [ -e "$MYSQL_CONFIG_FILE" ]; then
    success "MySQL already configured"
    return
  fi

  mysql.server start

  if ! mysqladmin -u root password a; then
    fail "Could not change MySQL password"
    return
  fi

  sudo mkdir -p "$MYSQL_DIR"

  echo "[client]
user=root
password=a

[mysqld]
socket = /tmp/mysql.sock
max_sp_recursion_depth = 255

max_connections       = 1000
key_buffer_size       = 16K
max_allowed_packet    = 1M
table_open_cache      = 4
sort_buffer_size      = 64K
read_buffer_size      = 256K
read_rnd_buffer_size  = 256K
net_buffer_length     = 2K
thread_stack          = 128K" | sudo tee "$MYSQL_CONFIG_FILE" > /dev/null

  mysql.server restart
}

function install_node {
  rm -rf $HOME/tmp/nodejs
  mkdir -p $HOME/tmp/nodejs
  cd $HOME/tmp/nodejs
  curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
  ./configure --prefix=$HOME/
  make install

  # NPM packages
  npm -g update
  npm -g install mocha
  npm -g install coffee-script
  npm -g install http-server
  npm -g install supervisor
}

