#!/usr/bin/env bash

function run {
  source ./dotfiles/.env
  source ./dotfiles/.aliases

  mkdir -p $BIN
  mkdir -p $OPT
  mkdir -p $TMP
  mkdir -p "$HOME/.ssh"

  bash recipes/dotfiles.sh install
  bash recipes/brew.sh install
  bash recipes/iterm.sh install
  bash recipes/sublime.sh install

  bash recipes/zsh.sh install
  bash recipes/tmux.sh install
  bash recipes/vim.sh install

  bash recipes/utils.sh install
  bash recipes/git.sh install
}

$@
