#!/usr/bin/env bash

function run {
  read -p "Please make a backup or you can loose your changes. Continue? (Y/n)" -n 1 -r
  echo    # (optional) move to a new line
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "Refreshing..."
    refresh
  fi
}

function refresh {
  bash recipes/dotfiles.sh install
  bash recipes/sublime.sh move_settings_files
}

$@
